#!/bin/bash
#
# Install and run vLLM inference server in Win11
#

function __source_env {
	cd $HOME/vllm/
	source $HOME/vllm/.venv/Scripts/activate
	[[ -d models/ ]] || mkdir models/
}

function __install_vllm {
	[[ -d $HOME/vllm/ ]] || mkdir $HOME/vllm/
	cd $HOME/vllm/
	python -m venv .venv  #创建 vllm 的虚拟运行环境
	source $HOME/vllm/.venv/Scripts/activate

	VLLM_WHL=vllm-0.10.2+cu124-cp312-cp312-win_amd64.whl
	pip install \
		torch==2.7.1+cu126 torchaudio==2.7.1+cu126 torchvision==0.22.1+cu126 \
		--index-url https://download.pytorch.org/whl/cu126
	if [[ -f $VLLM_WHL ]]; then
		printf "\n---> $VLLM_WHL existing... Start installing..."
	else
		printf "\n---> No file... Please download first..."
		printf "\n\n     https://github.com/SystemPanic/vllm-windows/releases/download/v0.10.2/vllm-0.10.2+cu124-cp312-cp312-win_amd64.whl\n\n"
	fi
	pip install vllm-0.10.2+cu124-cp312-cp312-win_amd64.whl
	python -m pip install --upgrade pip
	vllm --version  #确认 vllm 版本
	[[ $? -eq 0 ]] && printf "\n---> vLLM install successfully..."
}

function __mc_download {
	__source_env
	###ModelScope 模型社区 (魔搭社区 https://www.modelscope.cn/home):
	pip install modelscope  #install download tool
	python -c "from modelscope import snapshot_download; model_dir = snapshot_download('Qwen/Qwen3-4B-Instruct-2507-FP8', cache_dir='./models')"
	#已测试模型列表：
	# - Qwen/Qwen3-4B-Instruct-2507-FP8
	# - Qwen/Qwen3-0.6B
}

function __hf_download {
	__source_env
	printf "\n!!! 请确认已具有 Hugging Face 认证 Token !!!\n\n"
	read -p "输入 Hugging Face token: " HUGGINGFACE_TOKEN
	export $HUGGINGFACE_TOKEN
	read -p "请输入模型名称路径：" MODEL_PATH
	###Hugging Face 模型社区 (https://huggingface.co/):
	hf auth login --token $HUGGINGFACE_TOKEN
	hf download $MODEL_PATH --local-dir ./models/$MODEL_PATH
	#已测试模型列表：
	# - Qwen/Qwen3-4B-Instruct-2507
}

function __run_vllm {
	__source_env
	cd $HOME/vllm/models/
	#pip install bitsandbytes>=0.46.1
	
	#注意：运行不同的模型加载的选项可能存在差异而导致模型加载或请求失败
	vllm serve Qwen/Qwen3-4B-Instruct-2507 \
		--max-model-len 5000 \
		--quantization bitsandbytes \
		--gpu-memory-utilization 0.80 \
		--dtype float16 \
		--generation-config vllm \
		--uvicorn-log-level debug \
		--host 0.0.0.0 \
		--port 8000
	
	#选项说明：https://docs.vllm.com.cn/en/latest/cli/serve/ (vLLM 选项说明)
	#
	# --max-model-len 5000:
	# 	指定模型接收用户输入与模型输出最大 token 数量，该值由 GPU 硬件与推理框架计算获得，
	#   因此该值可手动指定。如果设置超出可支持的上限，那么模型输出可被截断或报错。
	#   与 "模型上下文窗口" 相区别。
	#
	# --gpu-memory-utilization 0.80: 
	# 	GPU 显存占用上限 80% (留 20% 余量，防 OOM)
	#
	# --dtype float16: 
	#	模型权重和激活值的数据类型
	#
	# --chat-template-content-format openai:
	#	模型使用的 chat 模板 (string 或 openai)，指定此选项对有些模型不适用。
	#
	#注意：以下两个选项需要同时使用
	# --enable-auto-tool-choice: 
	#	为支持的模型启用自动工具选择
	#
	# --tool-call-parser: 
	#	用 Hermes 格式解析工具调用 (与 Qwen3 模板对齐)
}

case $1 in
	--install-vllm)
		__install_vllm
		;;
	--mc-download)
		__mc_download
		;;
	--hf-download)
		__hf_download
		;;
	--run-vllm)
		__run_vllm
		;;
	--help)
		printf "\nrun_vllm_win.sh [OPTIONS]"
		printf "\n"
		printf "\n  OPTIONS:"
		printf "\n"
		printf "\n    --install-vllm    install vLLM"
		printf "\n    --mc-download     download models from ModelScope"
		printf "\n    --hf-download     download models from HuggingFace through token"
		printf "\n    --run-vllm        run vLLM inference server"
		printf "\n\n"
		;;
	*)
		printf "Usage error... Exit...\n"
esac
